# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://blog.hershman.io
title: Matthew Hershman
email: mhershman@gmail.com
description: > # "A personal landing page for Matthew Hershman"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url:
