# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: blog.hershman.io
title: Matthew Hershman
email: mhershman@gmail.com
description: > # "Personal landing page for Matthew Hershman"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/in/matthewhershman
  - title: resume
  url: 
